---
title: "R Notebook"
output: html_notebook
---

```{r}
library(CodeClanData)
library(dplyr)

drinks_content
```
```{r}
head(drinks_content)
```
```{r}
tail(drinks_content)
```
```{r}
View(drinks_content)

```

```{r}
dim(drinks_content)
```

```{r}
summary(drinks_content$Calories)

```
```{r}
boxplot(drinks_content$Calories)
```
```{r}
outliers <- boxplot(drinks_content$Calories, plot=FALSE)$out

outliers
```
```{r}
drinks_content[which(drinks_content$Calories %in% outliers),]
```
```{r}
drinks_content_nooutlier <- drinks_content[-which(drinks_content$Calories %in% outliers),]
```

```{r}
boxplot(drinks_content_nooutlier$Calories)
```
```{r}
drinks <- select(drinks_content_nooutlier, Beverage_category, Beverage, Beverage_prep, Calories)
```

```{r}
drinks
```
```{r}
View(drinks)
```

```{r}
espresso_drinks <- filter(drinks, Beverage_category == "Classic Espresso Drinks")

```

```{r}
espresso_drinks
```

```{r}
```


```{r}
drink_calories <- drinks %>%
  select(Beverage_category, Beverage, Beverage_prep, Calories) %>%
  mutate(calorie_diff = Calories-135) %>%
  group_by(Calories) %>%
  summarise(n())
```


```{r}
```

```{r}
low_cal_drinks
```
```{r}
View(low_cal_drinks)
```

```{r}
```


```{r}
drinks_grouped <- drinks %>%
  select(Beverage_prep, Calories) %>%
  group_by(Beverage_prep)
```


```{r}
drinks_grouped

  
```
```{r}
summary_all<- summarise(drinks_grouped, count=n())
summary_all
```
```{r}
x <- factor("drinks_grouped", "summary_all")
result.mean <- mean(x)
result_mean
```


drinks_summary <- drinks %>%
  select(Beverage_prep, Calories) %>%
  mutate(mean_cal = count / Calories) %>%
  group_by(Beverage_prep) %>%
  summarise(n())
  


  
```



