---
title: "R Notebook"
output: html_notebook
---


```{r}
library(readxl)
library(ggplot2)

#Graph_1
Graph_1 <- read_excel("green_bindle_consulting.xlsx" , sheet = "Data1")

Graph_1

```
```{r}

ggplot(Graph_1) + 
  aes(x = Year, y = Value, group = Item, fill = Item) +
  geom_col(position = "dodge", stat = "identity") 
scale_x_continuous(name = "Year", limit =2012, 2018)
  
```
```{r}
#Graph_2
Graph_2 <- read_excel("green_bindle_consulting.xlsx" , sheet = "Data2")

Graph_2
```
```{r}
ggplot(Graph_2) + 
  aes(x = Year, y = Value, group = Status, fill = Status) +
  geom_col(position = "dodge", stat = "identity") 
scale_x_continuous(name = "Year", limit =2012, 2018)
```
```{r}
library(ggplot2)
library(readxl)
```

#Graph_3
```{r}
Graph_3 <- read_excel("green_bindle_consulting.xlsx" , sheet = "Data3")

Graph_3
```
```{r}
ggplot(Graph_3) + 
  aes(x = Value, y = Item)  + 
  geom_col() 
 
```
Graph4
```{r}
Graph_4 <- read_excel("green_bindle_consulting.xlsx" , sheet = "Data4")

Graph_4
```
```{r}
 ggplot(Graph_4) +
  geom_histogram(aes(x = Date, fill =  Allocation, stat = "count")) +
  facet_grid(Region ~ Asset_Class)

```

