---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(dbplyr)
library(lubridate)

date1 <- ymd_hms("2017-04-22 22:01:18")
date2 <- ymd_hms("2001-11-07 10:09:56")

mammals <- DBI::dbConnect(RSQLite::SQLite(), "mammals.sqlite")

plots <- tbl(mammals, sql("SELECT * FROM plots"))
species <- tbl(mammals, sql("SELECT * FROM species"))
surveys <- tbl(mammals, sql("SELECT * FROM surveys"))
```
```{r}

plots
surveys
species


```
```{r}
#Q1
year(date1)
```
```{r}
month(date1)
```
```{r}
mday(date1)
```
```{r}
yday(date1)
```
```{r}
wday(date1)
```
```{r}
month(date1, label = TRUE, abbr = FALSE)
```
```{r}
#Q2
next_fortnight <- date1 + days(14)

next_fortnight
```
```{r}
previous_decade <- date2 - years(10)
previous_decade
```
```{r}
#Q3
this_year <-today()
this_year
```
```{r}
interval_years <- interval(this_year, previous_decade)

interval_years
```
```{r}
#Q4
nyc_date1 <- ymd_hms("2017-04-22 22:01:18", tz = "UTC")
new_date1 <- ymd_hms("2017-04-22 22:01:18", tz = "America/New_York")
                     
new_date1 - nyc_date1
```

```{r}
nyc_date2 <- ymd_hms("2001-11-07 10:09:56", tz = "UTC")

new_date2 = ymd_hms("2001-11-07 10:09:56", tz = "America/New_York")

new_date2 - nyc_date2
```
```{r}
#Q5

surveys <- tbl(mammals, sql("SELECT * FROM surveys"))

survey_tibble <- as_tibble(surveys) %>%
  collect() %>%
  mutate(full_date = make_datetime(year, month, day))

survey_tibble
```


```{r}
#Q6
#Month, day , year
```

```{r}
#Q7
surveyor_sex <- survey_tibble %>%
              mutate(logical_sex=as.logical(sex))

surveyor_sex

```

```{r}
surveyor_sex <- surveyor_sex %>%
              mutate(logcial_sex=as.logical(sex))
surveyor_sex
```
```{r}
#Q8
all_species <- left_join(surveys, species, by = "species_id", copy = TRUE)
```
```{r}
all_species
```
```{r}
all_species <- left_join(surveys, species, by = "species_id", plot_id,  "Control" = TRUE)

all_species
```
```{r}
#Q9
birds_year <- filter(surveys, taxa == birds, years)
summarise(birds_year, count=n()) 

birds_year
```

