---
title: "R Notebook"
output: html_notebook
---

```{r}
library(RPostgreSQL)


```

```{r}
library(keyring)
keyring_unlock("local")
username <- key_get("postgresql_username", keyring = "local")
password <- key_get("postgresql_password", keyring = "local")
keyring_lock("local")
db_connect <- dbConnect(drv = PostgreSQL(max.con = 1), user = username, password = password, dbname= "acme_employees", host = "localhost")
```
```{r}
dbListTables(conn = db_connect) 
```
```{r}
dbListFields(conn = db_connect, name = "teams")
```
```{r}
dbListFields(conn = db_connect, name = "employees")
```

```{r}
dbListFields(conn = db_connect, name = "feedbacks")
```
```{r}
data <- dbGetQuery(conn = db_connect, statement = "SELECT * FROM teams")

class(data)
```
```{r}
head(data)
```
```{r}
nrow(data)
```
```{r}
data <- dbGetQuery(conn = db_connect, statement = "SELECT * FROM employees")

class(data)
```
```{r}
head(data)
```
```{r}
data <- dbGetQuery(conn = db_connect, statement = "SELECT * FROM feedbacks")

class(data)
```
```{r}
nrow(data)
```
```{r}
dbGetQuery(db_connect, 
      "SELECT employees. *, feedbacks.*
      FROM employees INNER JOIN feedbacks
      ON employee_id = employee_id")
```

